### ISSUE TITLE
Bug: We have not published latest git version.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/dogs#28]
Our latest dog addition did **not** get released by the automation setup: https://github.com/FormidableLabs/dogs/pull/27

The most likely explanation goes back to issue #24 which boils down to "we should commitlint on the PR and _not_ only in pre-commit hooks".

Task:
- [x] Get current git branch released.
- [x] Consider fixing #24 to ensure this doesn't happen again.

**Comment by robwalkerco** [comment]
Closing as #24 is resolved and a subsequent version has successfully been released by CI
